Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,6 @@
 # This workflow represents a set of basic cmds
+name: sample Workflow
+
 # Trigger Events
 on:
   push:
@@ -11,6 +13,10 @@ jobs:
     runs-on: ubuntu-latest 
     steps:
       - name: Checkout action
-        uses: actions/checkout@v4  # push trigger' 1st step
+      - uses: actions/checkout@v4  # push trigger' 1st step
+        run: echo "checkout trigger"
+
+      - name: Simulating error
+        run: echo "error in this line and exit"; exit 1
 
 
