Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,15 +1,19 @@
----
+# This workflow represents a set of basic cmds
 name: sample Workflow
+
+# Trigger Events
 on:
   push:
     branches:
-      - main
+      - 'main'
+      
+# Jobs for this workflow
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-latest 
     steps:
       - name: Checkout action
-      - uses: actions/checkout@v4
-        run: echo "checkout trigger"
-        
-      
+      - uses: actions/checkout@v4  # push trigger' 1st step
+
+      - name: Simulating error
+        run: echo "error in this line and exit"; exit 1
